disabled_rules:
  - block_based_kvo # swift 3.2
  - closure_parameter_position
  - discarded_notification_center_observer
  - file_length
  - function_body_length
  - function_parameter_count
  - identifier_name
  - large_tuple
  - nesting
  - type_body_length
  - type_name
  - trailing_comma
  - weak_delegate
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - force_unwrapping
  - private_outlet
line_length: 110
type_body_length:
  warning: 300
  error: 400
excluded:
  - Carthage/
  - Frameworks/
  - Pods/
  - Playground.playground/
  - Lin.xcodeproj/
  - Lin.xcworkspace/
reporter: "xcode"
